### ISSUE TITLE
Feature Request - Shuffle rooms/base layout

### ISSUE THREAD

**Issue by serberoth** [beauxq/zilliandomizer#4]
First off I have to say that I love this randomizer!

I would like to know if it is feasible to shuffle the rooms/the layout of the base.  This could take the form of using existing rooms to generate a new base layout or something like that.  I was thinking something in the vein of the NES LoZ randomizer with what it does when shuffling dungeons.  I get that door/elevator placement might make this somewhat difficult for this game, but something to think about.  Thank you!

**Comment by beauxq** [comment]
A new option randomizes the path through the base. (only the red area so far)

**Comment by beauxq** [comment]
With the map generation feature (released in Archipelago today) it seems like a good time to mark this as completed.
https://github.com/ArchipelagoMW/Archipelago/releases/tag/0.5.1
