### ISSUE TITLE
Colour palette cycling issue

### ISSUE THREAD

**Issue by serberoth** [beauxq/zilliandomizer#5]
Seed: 294f5e2260d419a3

After playing through the game and dying three times then continuing the game placed me back at the landing site; however, the colour palette was cycling oddly as in the attached image.

![image](https://user-images.githubusercontent.com/142649/172460502-35fd4ec4-d52f-4b31-af3c-a5b2523ffc49.png)

Using Bizhawk 2.8 (x64) on Windows 10.

**Comment by beauxq** [comment]
fixed in https://github.com/beauxq/zilliandomizer/commit/1dd2ce01c9d818caba5844529699b3ad026d6a07
